window.TOOLS = [
  { id: 1, name: "ChatGPT", category: "Text & Chat", badge: "Freemium", rating: 4.8, desc: "Conversational AI model for drafting, answering, and brainstorming." },
  { id: 2, name: "Claude", category: "Text & Chat", badge: "Freemium", rating: 4.9, desc: "Next-gen AI assistant built for safety, reasoning, and long context tasks." },
  { id: 3, name: "Midjourney", category: "Image Generation", badge: "Paid", rating: 4.8, desc: "High-quality text-to-image artwork and photorealistic visual generator." },
  { id: 4, name: "DALL·E 3", category: "Image Generation", badge: "Paid", rating: 4.6, desc: "OpenAI's advanced text-to-image model integrated into ChatGPT." },
  { id: 5, name: "GitHub Copilot", category: "Code & Dev", badge: "Paid", rating: 4.7, desc: "AI pair programmer suggesting autocomplete lines and functions." },
  { id: 6, name: "Cursor", category: "Code & Dev", badge: "Freemium", rating: 4.9, desc: "An AI-first code editor designed for high productivity." },
  { id: 7, name: "ElevenLabs", category: "Audio & Voice", badge: "Freemium", rating: 4.8, desc: "Realistic text-to-speech voice generator and cloning software." },
  { id: 8, name: "Sora", category: "Video & Animation", badge: "Paid", rating: 4.7, desc: "Create realistic and imaginative videos from text prompts." },
  { id: 9, name: "Notion AI", category: "Productivity", badge: "Paid", rating: 4.5, desc: "Integrated AI workspace helper for writing, summarizing, and editing." },
  { id: 10, name: "Perplexity AI", category: "Text & Chat", badge: "Freemium", rating: 4.8, desc: "Conversational search engine with real-time citations and sources." },
  { id: 11, name: "Stable Diffusion", category: "Image Generation", badge: "Free", rating: 4.6, desc: "Open-source, powerful image generation deep learning model." },
  { id: 12, name: "v0 by Vercel", category: "Code & Dev", badge: "Freemium", rating: 4.7, desc: "Generative UI system powered by AI that outputs React/Tailwind code." },
  { id: 13, name: "Suno", category: "Audio & Voice", badge: "Freemium", rating: 4.8, desc: "Generate full songs with lyrics and vocals from text descriptions." },
  { id: 14, name: "Runway Gen-2", category: "Video & Animation", badge: "Freemium", rating: 4.5, desc: "Text-to-video and image-to-video generative AI Suite." },
  { id: 15, name: "Grammarly", category: "Productivity", badge: "Freemium", rating: 4.6, desc: "AI writing tool for grammar, tone, clarity, and phrasing." },
  { id: 16, name: "Google Gemini", category: "Text & Chat", badge: "Freemium", rating: 4.7, desc: "Google's multimodal model capable of understanding text, code, audio, and video." },
  { id: 17, name: "Leonardo.Ai", category: "Image Generation", badge: "Freemium", rating: 4.7, desc: "Feature-rich asset creation tool for visual production and artwork." },
  { id: 18, name: "Replit Ghostwriter", category: "Code & Dev", badge: "Paid", rating: 4.4, desc: "In-browser AI coding assistant integrated directly into Replit IDE." },
  { id: 19, name: "Whisper", category: "Audio & Voice", badge: "Free", rating: 4.9, desc: "Robust speech recognition model trained on thousands of hours of audio." },
  { id: 20, name: "Pika Labs", category: "Video & Animation", badge: "Freemium", rating: 4.6, desc: "Idea-to-video platform that brings creative concepts to life." },
  { id: 21, name: "Otter.ai", category: "Productivity", badge: "Freemium", rating: 4.5, desc: "Automated meeting notes, audio transcription, and real-time summaries." },
  { id: 22, name: "Mistral AI", category: "Text & Chat", badge: "Free", rating: 4.7, desc: "High-performance open-weights LLMs for global developers." },
  { id: 23, name: "Canva Magic Studio", category: "Image Generation", badge: "Freemium", rating: 4.5, desc: "AI visual design tools for generating graphics and magic edits." },
  { id: 24, name: "Tabnine", category: "Code & Dev", badge: "Freemium", rating: 4.3, desc: "AI code completion assistant emphasizing code privacy and security." },
  { id: 25, name: "Descript", category: "Audio & Voice", badge: "Freemium", rating: 4.7, desc: "Edit audio and video files by editing text transcripts." },
  { id: 26, name: "HeyGen", category: "Video & Animation", badge: "Freemium", rating: 4.8, desc: "Create realistic AI avatar videos for teams and businesses." },
  { id: 27, name: "Zapier Central", category: "Productivity", badge: "Freemium", rating: 4.4, desc: "AI bot workplace automation tool across thousands of apps." },
  { id: 28, name: "DeepL Translate", category: "Text & Chat", badge: "Freemium", rating: 4.9, desc: "Accurate neural network translation system for global communications." },
  { id: 29, name: "Krea AI", category: "Image Generation", badge: "Freemium", rating: 4.8, desc: "Real-time AI visual generation and upscaling tool." },
  { id: 30, name: "Phind", category: "Code & Dev", badge: "Free", rating: 4.7, desc: "Search engine optimized specifically for developer technical questions." },
  { id: 31, name: "Lovo.ai", category: "Audio & Voice", badge: "Paid", rating: 4.4, desc: "Award-winning voice generator software with human-like voices." },
  { id: 32, name: "Synthesia", category: "Video & Animation", badge: "Paid", rating: 4.6, desc: "Turn text into video presentation slides using custom AI avatars." }
];
